/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.bupt.hutaow;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int btn_con_length=0x7f040001;
        public static final int btn_con_marginLeft=0x7f040002;
        public static final int btn_length=0x7f040003;
        public static final int layout_width=0x7f040000;
    }
    public static final class id {
        public static final int btn_0=0x7f050015;
        public static final int btn_1=0x7f050010;
        public static final int btn_2=0x7f050011;
        public static final int btn_3=0x7f050012;
        public static final int btn_4=0x7f05000b;
        public static final int btn_5=0x7f05000c;
        public static final int btn_6=0x7f05000d;
        public static final int btn_7=0x7f050006;
        public static final int btn_8=0x7f050007;
        public static final int btn_9=0x7f050008;
        public static final int btn_bksp=0x7f050003;
        public static final int btn_c=0x7f050005;
        public static final int btn_ce=0x7f050004;
        public static final int btn_div=0x7f050009;
        public static final int btn_dot=0x7f050017;
        public static final int btn_equal=0x7f050019;
        public static final int btn_mc=0x7f050014;
        public static final int btn_mul=0x7f05000e;
        public static final int btn_plus=0x7f050018;
        public static final int btn_pm=0x7f050016;
        public static final int btn_rm=0x7f05000f;
        public static final int btn_sub=0x7f050013;
        public static final int btn_xm=0x7f05000a;
        public static final int et_led=0x7f050000;
        public static final int tv_mem=0x7f050002;
        public static final int tv_tmp=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
